EasyAdmin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('apps.main.urls')),
    path("main/", include('apps.main.urls')),
]

SPWebv2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('apps.main.urls')),
    path("main/", include('apps.main.urls')),
]

apps/main/urls.py
from django.urls import path
from . import views

# Register the application namespace
app_name = "main"

urlpatterns = [
    path("", views.landing, name="home"),
    path("easyadmin/", views.easy_admin, name="easy_admin"),
    path("ajax_admin/",views.ajax_admin,name="ajax_admin"),
    path("pricing", views.pricing, name="pricing"),
    path("test", views.test, name="test"),
]

apps/users/urls.py
from django.urls import path
from .views import SignUpView, user_login
from django.contrib.auth.views import LogoutView

# Register the application namespace
app_name = "users"

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', user_login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

apps/main/models.py
from django.db import models
from solo.models import SingletonModel

class SiteConfig(SingletonModel):

    """ The Site Configuration """

    navbar_image = models.ImageField(verbose_name="NavBar Image",
                                     help_text="The image to use on the main NavBar",
                                     blank=True
                                    )

    def __str__(self):
        return "Site Configuration"

    class Meta:

        """ Add special attributes"""
        verbose_name = "Site Configuration"

apps/tenants/models.py
from django.db import models

class Tenant(models.Model):

    """
    Tenant model to enable multi-tenancy
    """

    name = models.CharField(max_length=100)
    subdomain_prefix = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Tenant"
        verbose_name_plural = "Tenants"


class TenantAwareModel(models.Model):

    """
    Abstract base class for all models that need to be tenant aware
    """

    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)

    class Meta:
        abstract = True

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from .managers import CustomUserManager
from apps.tenants.models import TenantAwareModel


class CustomUser(AbstractBaseUser, TenantAwareModel, PermissionsMixin):

    first_name = models.CharField(max_length=30, verbose_name='First Name')
    last_name = models.CharField(max_length=150, verbose_name='Last Name')
    email = models.EmailField(_('email address'), unique=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    # Set the Username to email
    USERNAME_FIELD = 'email'

    # Set the required fields
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

apps/main/forms.py
from django import forms
from . import models

class site_config_form(forms.ModelForm):

    """
    Model form for the SiteConfig class
    """

    class Meta:
        model = models.SiteConfig
        fields = ('navbar_image',)

apps/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .models import CustomUser
from django.contrib.auth import authenticate, login

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)


class LoginForm(forms.Form):

    """
    Form got logging into the site
    """

    username = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)
    remember_me = forms.BooleanField(required=False)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        user = authenticate(username=username, password=password)

        if not user or not user.is_active:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")

        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        user = authenticate(username=username,password=password)

        return user

apps/main/views.py
from django.shortcuts import render, redirect
from . import forms
from . import models
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.http import require_POST

@require_POST
def ajax_admin(request):

    id = request.POST.get("id")

    print(id)
    print("Woohoo - this worked")

    return JsonResponse({"status": "ok","html_content": f"<h1>{id}</h1>"})


def landing(request):

    """
    Render the Landing Page
    """

    return render(request, 'main/landing/index.html', {"landing_page": True})


def pricing(request):
    return render(request,"main/landing/pricing.html")

def test(request):
    return render(request, "main/base_admin.html")

def easy_admin(request):

    if request.method == "POST":

        form = forms.site_config_form(request.POST)

        if form.is_valid():

            # Get the cleaned data from the form
            cleaned_data = form.cleaned_data

            # Get the SiteConfiguration
            site_config = models.SiteConfig.get_solo()

            # Update the site Configuration
            site_config.navbar_image = cleaned_data["navbar_image"]

            # Save the updated record
            site_config.save()

            # Return to the home page as authenticated
            return redirect(reverse("home"))

        # Form is invalid
        form = forms.site_config_form()
        return render(request,"main/admin/easy_admin.html", {"form": form, "admin": True})

    else:

        # Get request - just show the form
        form = forms.site_config_form()
        return render(request, "main/admin/easy_admin.html", {"form": form, "admin": True})

apps/tenants/views.py
from django.shortcuts import render

# Create your views here.

apps/users/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView
from .forms import CustomUserCreationForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import LoginForm
from django.views.decorators.http import require_http_methods


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


@require_http_methods(["GET", "POST"])
def user_login(request):

    # Create a new instance of the form using POST if set, else None
    form = LoginForm(request.POST or None)

    if request.POST and form.is_valid():

        # We already validated credentials in the form 'clean' method
        user = form.login(request)

        # Check whether remember_me was set
        remember_me = form.cleaned_data["remember_me"]

        if user:

            # Success - Log the user in
            login(request, user)

            if not remember_me:

                # Set session expiry to 0  -Session is closed when browser is closed
                # Otherwise session will not expire until SESSION_COOKIE_AGE is reached
                request.session.set_expiry(0)
                request.session.modified = True

            return render(request, 'main/index.html')

    return render(request, 'users/login.html', {'form': form})

apps/main/templates/main/admin/easy_admin.html
{% extends "main/base_admin.html" %}
{% load static %}

{# Set the browser title #}
{% block browser-title %}
    EasyAdmin
{% endblock %}

{# Set the admin title #}
{% block admin-title %}
    EasyAdmin
{% endblock %}

<!-- Add the menu items to the side bar -->
<!-- No need to exit, thats catered for in the base template -->
{% block sidebar-menu %}

    <a href="#dashboard" id="a-dashboard" data-toggle="tab" class="list-group-item list-group-item-action list-group-item-primary active">
        <i class="fas fa-tachometer-alt fa-lg p-2"></i>
        Dashboard
    </a>

    <a href="#siteconfig" id="a-siteconfig" data-toggle="tab" class="list-group-item list-group-item-action list-group-item-primary">
        <i class="fas fa-cog fa-lg p-2"></i>
        Site Configuration
    </a>

    <a href="#users" id="a-users" data-toggle="tab" class="list-group-item list-group-item-action list-group-item-primary">
        <i class="fas fa-users fa-lg p-2"></i>
        Users
    </a>

    <a href="#services" id="a-services" data-toggle="tab" class="list-group-item list-group-item-action list-group-item-primary">
        <i class="fas fa-sitemap fa-lg p-2"></i>
        Services
    </a>

    <a href="#profile" id="a-profile" data-toggle="tab" class="list-group-item list-group-item-action list-group-item-primary">
        <i class="fas fa-user-cog fa-lg p-2"></i>
        Profile
    </a>

    <a href="#logout" id="a-logout" data-toggle="tab" class="list-group-item list-group-item-action list-group-item-primary">
        <i class="fas fa-sign-out-alt fa-lg p-2"></i>
        Logout
    </a>

    <a href="#servicestatus" id="a-servicestatus" data-toggle="tab" class="list-group-item list-group-item-action list-group-item-primary">
        <i class="fas fa-question-circle fa-lg p-2"></i>
        Service Status
    </a>

{% endblock %}

{# Add the javascript we need#}
{% block domready %}



{% endblock %}

apps/main/templates/main/admin_panel/dashboard.html
<div class="row pt-3 pb-3">
    <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-primary">Dashboard</h5>
            <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p>
            <a class="card-link">Card link</a>
            <a class="card-link">Another link</a>
          </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-primary">Dashboard</h5>
            <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p>
            <a class="card-link">Card link</a>
            <a class="card-link">Another link</a>
          </div>
        </div>
    </div>

    <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-primary">Dashboard</h5>
            <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p>
            <a class="card-link">Card link</a>
            <a class="card-link">Another link</a>
          </div>
        </div>
    </div>


    <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-primary">Dashboard</h5>
            <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p>
            <a class="card-link">Card link</a>
            <a class="card-link">Another link</a>
          </div>
        </div>
    </div>

</div>

apps/main/templates/main/base_admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Application Title - which can be overridden -->
    <title>
        {% block browser-title %}
            Admin Panel
        {% endblock %}
    </title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static "css/streamlinepartners.css" %}">

    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="{% static "css/mdb-free.css"%}">

    <!-- Site Admin CSS-->
    <link rel="stylesheet" href="{% static "css/site_admin.css"%}">

</head>
<body>

<!-- Page Wrapper Start -->
<div class="d-flex" id="wrapper">

    <!-- SideBar Wrapper -->
    <div class="primary-color" id="sidebar-wrapper">

        <!-- Top Left Heading -->
        <div class="sidebar-heading bg-dark text-white align-self-center nowrap" style="height: 70px" align="middle">
            {% block admin-title %}
                {# Can be overridden#}
                Admin Panel
            {% endblock %}
        </div>

        <!-- Sidebar Menu List -->
        <div id="sidebarlist" class="list-group list-group-flush">

            {% block sidebar-menu %}
                {# Add SideBar menu items here - similiar to exit below #}

            {% endblock %}

            {# Always has an exit #}
            <a href="#" id="a-exit" data-toggle="modal" data-target="#exit-modal" class="list-group-item list-group-item-action list-group-item-primary">
                <i class="fas fa-window-close fa-lg p-2"></i>
                Exit
            </a>
        </div>
        <!-- End Sidebar Menu List-->
    </div>
    <!-- End SideBar Wrapper -->

    <!-- Page Content Start-->
    <div id="page-content-wrapper">

        {# navbar - can be overridden #}
        {% block navbar %}
            <nav class="navbar navbar-expand-lg navbar-light primary-color navbar-dark" style="height: 70px">

              <!-- Hide Sidebar Button - shown by default -->
              <button class="btn btn-danger btn-sm justify-content-center"
                      id="menu-toggle-hide" data-toggle="tooltip" data-placement="right" title="Hide the SideBar" class="text-white" style="display: block;">
                  <i id="sidebarhide" class="fas fa-arrow-left fa-lg mr-2 align-middle"></i>
                  Sidebar
              </button>

              <!-- Show SideBar button - hidden by default -->
              <button class="btn btn-danger btn-sm justify-content-center"
                      id="menu-toggle-show" data-toggle="tooltip" data-placement="right" title="Show the SideBar" class="text-white" style="display: none">
                  <i class="fas fa-arrow-right fa-lg mr-2 align-middle"></i>
                  Sidebar
              </button>

                {# Navbar Image - can be overridden #}
                {% block navbarimage %}
                    <img src="{% static "img/logo/EasyAdmin_Transparent_Wix.png" %}" style="width: 250px">
                {% endblock %}

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

              <ul class="navbar-nav mt-2 mt-lg-0">
                  {% block navbarlinks %}
                      {# Additional links go here  #}
                  {% endblock %}
              </ul>

            </div>
          </nav>
          {# End Navbar #}

        {% endblock %}

        <!-- Main Panel Container -->
        <div class="container-fluid">

            <!-- Main Panel Contents -->
            <div class="tab-content" id="admin-pane-content">

                <!-- You can choose to overwrite the whole panel contents with block main-panel -->
                {% block main-panel %}
                    <div class="row pt-3 pb-3">
                        <div class="col">
                            <div class="card">

                              <!-- Or you can overwrite into the main panel card -->
                              {% block main-panel-card %}
                                <div class="card-body">
                                    <h5 class="card-title text-primary">Main Panel</h5>
                                    <p class="card-text">This is the main panel.</p>
                                </div>
                              {% endblock %}

                            </div>
                        </div>
                    </div>
                {% endblock %}

            </div>
            <!- End Main Panel Contents -->

        </div>
        <!-- End Main Panel Container -->

        <!-- Modal Exit Form -->
        <div class="modal fade" id="exit-modal" tabindex="-1" role="dialog" aria-labelledby="exitmodal" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">

                    <h5 class="modal-title" id="exitadminmodaltitle">
                        <!-- Can override the exit modal heading -->
                        {% block exit-modal-heading %}
                            Exit Admin
                        {% endblock %}
                    </h5>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <!-- Can override the exit modal text -->
                    {% block exit-modal-text %}
                        Are you sure you want to exit the admin interface?
                    {% endblock %}

                </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                        <a type="button" href="{% url "main:home" %}" class="btn btn-primary">Yes</a>
                    </div>
                </div>

            </div>
        </div>
        <!-- End Modal Exit form -->

    </div>
    <!-- Page Content End -->
</div>
<!-- Page Wrapper End -->

    <!-- Feather Icon Support -->
  <script src="{% static "js/feather-icon/feather.min.js" %}"></script>

  <!-- jQuery -->
  <script type="text/javascript" src="{% static "js/jquery.min.js" %}" ></script>

    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static "js/popper.min.js" %}" ></script>

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}" ></script>

    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static  "js/mdb.min.js"%}" ></script>

    <!-- For access to cookies -->
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>

    <!-- Custom JavaScript -->
    <script type="text/javascript" src="{% static  "js/custom.js"%}" ></script>

    <script>

        // Executes when DOM is fully loaded
        $(document).ready(function(){

            // Ensure feather icons are displayed
            feather.replace()

            // Enable bootstrap tooltips
            $(function () {
                $('[data-toggle="tooltip"]').tooltip()
            })

            // Get and store the CSRFToken for Ajax Queries
            var csrftoken = Cookies.get("csrftoken");

            // Returns the methods that are safe and don't require csrftokens
            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            // Hides the side bar
            $("#menu-toggle-hide").click(function(e) {

                // Prevent default button processing
                e.preventDefault();

                $("#wrapper").toggleClass("toggled");

                // Make the hide sidebar button invisible
                var hidebutton=document.getElementById("menu-toggle-hide")
                hidebutton.style.display = "none"

                // Make the show sidebar button visible
                var showbutton=document.getElementById("menu-toggle-show")
                showbutton.style.display = "block"
            });

            // Shows the side bar
            $("#menu-toggle-show").click(function(e) {

                // Prevent default button processing
                e.preventDefault();

                $("#wrapper").toggleClass("toggled");

                // Make the show sidebar button visible
                var hidebutton=document.getElementById("menu-toggle-hide")
                hidebutton.style.display = "block"

                // Make the hide sidebar button invisible
                var showbutton=document.getElementById("menu-toggle-show")
                showbutton.style.display = "none"
            });

            {% block domready %}

                {# Javascript from child pages goes here #}

            {% endblock %}
        });

    </script>

</body>
</html>

apps/main/templates/main/landing/main_page.html
{% load static %}

<!--Mask applied to darken the background image-->
<div id="intro" class="view" >

    <div class="mask rgba-black-strong">

        <div class="container-fluid d-flex align-items-center justify-content-center h-100">

            <div class="row d-flex justify-content-center text-center">

                <div class="col-md-10">

                    <!-- Heading -->
                    <h2 class="display-4 font-weight-bold white-text pt-5 mb-2">Easy Service Management</h2>

                    <!-- Divider -->
                    <hr class="hr-light">

                    <!-- Description -->
                    <h5 class="white-text my-4">Automate your business by getting out of those spreadsheets, track and manage each interaction in a secure platform. Get access to Cherwell's ‘no code’ platform at a fraction of the commitment. StreamLine Partners is now offering full access to your own tenanted Cherwell Enterprise instance from as little as 3 licences. Full option to 'Self-Service' onboard or consultant guided onboarding packages available. Simple credit card sign up with the option to bill monthly or annually.</h5>
                    <button type="button" class="btn btn-outline-white">Read more<i class="fas fa-book ml-2"></i></button>

                </div>

            </div>

        </div>

    </div>

</div>

apps/main/templates/main/navbars/brand.html
{% load static %}
<!-- Navbar brand -->
<a class="navbar-brand" href="#">
    <a href="{% url "main:home" %}">
        <img src="{% static "img/logo/EasyAdmin_Transparent_Wix.png" %}" style="width: 250px">
    </a>
</a>

apps/main/templates/main/navbars/brand_no_home.html
{% load static %}
<!-- Navbar brand -->
<img src="{% static "img/logo/EasyAdmin_Logo.png" %}">

apps/main/templates/main/navbars/landing_page_navbar.html
{% load static %}

<!--Transparent Background Navbar - for Landing Page-->
{% if landing_page%}
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar">
{% else %}
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top primary-color">
{% endif %}

    <div class="container">

        <!-- Load the Brand for the NavBar -->
        {% include "main/navbars/brand.html" %}

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

            <!-- Links -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "main:home"%}#intro">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "main:home" %}#best-features">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "main:home" %}#examples">Examples</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "main:home" %}#gallery">Gallery</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "main:home" %}#contact">Contact</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="{% url "main:easy_admin"%}">Admin</a>
{#                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="{% url "main:site_config"%}" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>#}
{#                    <div class="dropdown-menu">#}
{#                        <a class="dropdown-item" href="{% url "main:site_config"%}">Site Configuration</a>#}
{#                    </div>#}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="pricing">Pricing</a>
                </li>

            </ul>
            <!-- End Links -->

            <!-- Social Icon  -->
            <ul class="navbar-nav nav-flex-icons">
                <li class="nav-item">
                    <a class="nav-link"><i class="fab fa-facebook-f"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"><i class="fab fa-twitter"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"><i class="fab fa-instagram"></i></a>
                </li>
            </ul>
            <!-- End Social Icons -->

            <!-- End Collapsible content -->
        </div>
    </div>
</nav>

apps/main/templates/main/navbars/navbar.html
{% load static %}

<!-- Primary Color Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top primary-color">

    <div class="container">

        <!-- Navbar brand -->
        <a class="navbar-brand" href="#">
            <a href="{% url "main:home" %}">
                <img src="{% static "img/logo/EasyAdmin_Logo.png" %}">
            </a>
        </a>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

            <!-- Links -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "main:home"%}#intro">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "main:home" %}#best-features">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "main:home" %}#examples">Examples</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "main:home" %}#gallery">Gallery</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "main:home" %}#contact">Contact</a>
                </li>
            </ul>
            <!-- End Links -->

            <!-- Social Icon  -->
            <ul class="navbar-nav nav-flex-icons">
                <li class="nav-item">
                    <a class="nav-link"><i class="fab fa-facebook-f"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"><i class="fab fa-twitter"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"><i class="fab fa-instagram"></i></a>
                </li>
            </ul>
            <!-- End Social Icons -->

            <!-- End Collapsible content -->
        </div>
    </div>
</nav>

apps/users/templates/users/login.html
{% extends "main/base.html" %}
{% load main_tags %}
{% load main_widgets %}

{% block body %}
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center text-white p-4 bg-dark rounded">
                    <h1 class="display-4 py-2 text-wrap">Login to <br> {% AppName %}</h1>
                    <div class="px-2">
                        <form action="{% url "users:login" %}" method="post" class="justify-content-center">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="sr-only">Email Address</label>
                                <input type="email" class="form-control" placeholder="Email Address" name="username" autofocus required>
                            </div>
                            <div class="form-group">
                                <label class="sr-only">Password</label>
                                <input type="password" class="form-control" placeholder="password" name="password" required>
                            </div>

                            {% if form.non_field_errors %}
                                {% for error in form.non_field_errors %}
                                    {# Show any errors to the user #}
                                    <div class="alert alert-danger alert-dismissible fade show">
                                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                                        <strong>Error!</strong><br> {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <div class="form-group">
                                <label class="form-check-label">
                                <input class="form-check-input" type="checkbox" name="remember_me">
                                    Remember Me
                                </label>
                            </div>
                            <span class="float-right">
                                {% widget_form_login %}
                            </span>
                        </form>

                    </div>
                </div>
            </div>
    </div>
{% endblock %}